name: CI

on: 
  push:

jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        version: ['3.9','3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #predefined github actions

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: ${{ matrix.version }}
          
      - name: Install flake8
        run: | 
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Run flake8
        run: flake8 app.py
